# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

namespace :db do
  desc 'Reseta o banco de dados e carrega seeds padrão'
  task reset_with_seeds: :environment do
    puts 'Dropping database...'
    Rake::Task['db:drop'].invoke

    puts 'Creating database...'
    Rake::Task['db:create'].invoke

    puts 'Migrating database...'
    Rake::Task['db:migrate'].invoke

    puts 'Loading seeds...'
    Rake::Task['db:seed'].invoke

    puts 'Banco restaurado com seeds padrão.'
  end
end
